name: Find ticker

on:
  pull_request:
    types: [opened]
    branches: [develop,stage,master]
    paths:
      - 'test-1/**'

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[a-z\d-_.\\/]+'
          head-branch-regex: 'sheesha-\d+'
          title-template: '[%headbranch%] '
          body-template: |
            Merging into '%basebranch%'
            [Link to %headbranch%](https://sheeshafinance.atlassian.net/browse/%headbranch%)
          body-update-action: 'suffix'
          body-uppercase-base-match: false
